export {
    fetchCourseById,
    fetchDashboardStats,
    fetchMyEnrollments,
    fetchMyNotifications,
    fetchMyRegistrations,
    fetchProgress,
    fetchQuizAttempts,
    fetchQuizDetail,
    fetchQuizzes,
    markAllNotificationsRead,
    markLessonComplete,
    markNotificationRead,
    submitQuiz,
    createRegistrationPaymentCheckout,
} from "@/lib/api";
